### CREATE SINGLE PERSON
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jake",
    "number": "123"
}

### DELETE SINGLE PERSON
DELETE http://localhost:3001/api/persons/1

### GET ALL PERSONS
GET http://localhost:3001/api/persons

### GET SINGLE PERSON
GET http://localhost:3001/api/persons/1

### GET SINGLE PERSON 404
GET http://localhost:3001/api/persons/999