POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Test",
    "author": "Test Joseph",
    "url": "Test@test.com",
    "likes": 1
}

####

GET http://localhost:3001/api/blogs

