POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "My Jounrey from Mechanical to Software Engineer",
    "author": "Jake Joseph",
    "url": "jakejoseph.com",
    "likes": 100,
    "userId": "5ed900800f4e59081bc452cb"
}
###


GET http://localhost:3001/api/blogs/




### USERS ###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "jjoseph",
    "password": "jjcs2020",
    "name": "Jake Joseph"
}



### LOGIN ###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "jjoseph",
    "password": "jjcs2020"
}