POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Laura's Journey",
    "author": "Laura Joseph",
    "url": "Laurajoseph.com",
    "likes": 998
}

####

GET http://localhost:3001/api/blogs

